---
version: '2'
services:
  elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
   network_mode: "host"      
   container_name: elasticsearch
   environment:
     - cluster.name=docker-cluster
     - bootstrap.memory_lock=true
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
   ulimits:
     memlock:
       soft: -1
       hard: -1
   volumes:
     - esdata:/usr/share/elasticsearch/data
   ports:
     - 9200:9200

  kibana:
   image: docker.elastic.co/kibana/kibana:6.5.0
   network_mode: "host"      
   environment:
     SERVER_HOST: "127.0.0.1"
     ELASTICSEARCH_URL: http://127.0.0.1
   depends_on: 
     - elasticsearch

  #logstash:
  # image: docker.elastic.co/logstash/logstash:6.5.0
  # network_mode: "host"      
  # volumes:
  #   - ./logstash/pipeline:/usr/share/logstash/pipeline:ro

  filebeat:
   image: docker.elastic.co/beats/filebeat:6.5.0
   network_mode: "host"
   volumes:
     - ./filebeat.yaml:/usr/share/filebeat/filebeat.yml
     - ./jnvd.json:/tmp/jnvd.json
   depends_on: 
     - elasticsearch
     - kibana

volumes:
  esdata:
   driver: local
