---
version: '2'
services:
  elasticsearch:
   container_name: elasticsearch
   image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
   environment:
     - cluster.name=docker-cluster
     - bootstrap.memory_lock=true
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     - network.host=0.0.0.0
     - discovery.zen.minimum_master_nodes=1
     - discovery.type=single-node
   ulimits:
     memlock:
       soft: -1
       hard: -1
   networks:
     - elk
   volumes:
     - esdata:/usr/share/elasticsearch/data
   ports:
     - 9200:9200

  kibana:
   container_name: kibana
   image: docker.elastic.co/kibana/kibana:6.5.1
   volumes:
     - ./kibana.yml:/usr/share/kibana/config/kibana.yml 
   networks:
     - elk
   ports:
     - 5601:5601

  logstash:
   container_name: logstash
   image: docker.elastic.co/logstash/logstash:6.5.1
   networks:
     - elk
   volumes:
     - ./pipeline:/usr/share/logstash/pipeline:ro
     - ./split_files:/tmp/cve

  #filebeat:
  # container_name: filebeat
  # image: docker.elastic.co/beats/filebeat:6.5.1
  # volumes:
  #   - ./filebeat.yaml:/usr/share/filebeat/filebeat.yml
  #   - ./jnvd.json:/tmp/jnvd.json
  # networks:
  #   - elk

networks:
  elk:
    driver: bridge 
volumes:
  esdata:
   driver: local
